_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 48
                - 49
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 48
                - 49
                - 53
                - 55
                - 71
                - 105
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.9.18
            "5": 0.19.11
            "6": 4.51.3
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": darwin-x86_64
architecture:
    value: Autoencoder_KL
batch_size:
    value: 8
dataset:
    value: FDG_2D_slices
epochs:
    value: 100
learning_rate:
    value: 5e-05
